# See: https://github.com/WordPress/plugin-check-action
name: Plugin Check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  plugin-check:
    name: Run Plugin Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Build assets
        run: |
          npm ci
          npm run build

      - name: Run Plugin Check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: "./"
          exclude-directories: "node_modules,src,.idea"
          exclude-files: ".nvmrc,.gitignore,.distignore,.gitattributes"
